/* *
 * Scanner for the class project in COP5556 Programming Language Principles 
 * at the University of Florida, Fall 2017.
 * 
 * This software is solely for the educational benefit of students 
 * enrolled in the course during the Fall 2017 semester.  
 * 
 * This software, and any software derived from it,  may not be shared with others or posted to public web sites,
 * either during the course or afterwards.
 * 
 *  @Beverly A. Sanders, 2017
  */

package cop5556fa17;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;

import javax.print.DocFlavor.INPUT_STREAM;

public class Scanner {
	
	@SuppressWarnings("serial")
	public static class LexicalException extends Exception {
		
		int pos;

		public LexicalException(String message, int pos) {
			super(message);
			this.pos = pos;
		}
		
		public int getPos() { return pos; }

	}
	
	public static enum State{
		START, AFTER_EQ, IN_IDENT, IN_DIGIT, AFTER_GREATER, AFTER_LESS, AFTER_MINUS, AFTER_MULTIPLY, AFTER_EXCL, AFTER_RETURN, AFTER_DIV, AFTER_COMMENT, IN_STRING;
	}	
	
	public static enum Kind {
		IDENTIFIER, INTEGER_LITERAL, BOOLEAN_LITERAL, STRING_LITERAL, 
		KW_x/* x */, KW_X/* X */, KW_y/* y */, KW_Y/* Y */, KW_r/* r */, KW_R/* R */, KW_a/* a */, 
		KW_A/* A */, KW_Z/* Z */, KW_DEF_X/* DEF_X */, KW_DEF_Y/* DEF_Y */, KW_SCREEN/* SCREEN */, 
		KW_cart_x/* cart_x */, KW_cart_y/* cart_y */, KW_polar_a/* polar_a */, KW_polar_r/* polar_r */, 
		KW_abs/* abs */, KW_sin/* sin */, KW_cos/* cos */, KW_atan/* atan */, KW_log/* log */, 
		KW_image/* image */,  KW_int/* int */, 
		KW_boolean/* boolean */, KW_url/* url */, KW_file/* file */, OP_ASSIGN/* = */, OP_GT/* > */, OP_LT/* < */, 
		OP_EXCL/* ! */, OP_Q/* ? */, OP_COLON/* : */, OP_EQ/* == */, OP_NEQ/* != */, OP_GE/* >= */, OP_LE/* <= */, 
		OP_AND/* & */, OP_OR/* | */, OP_PLUS/* + */, OP_MINUS/* - */, OP_TIMES/* * */, OP_DIV/* / */, OP_MOD/* % */, 
		OP_POWER/* ** */, OP_AT/* @ */, OP_RARROW/* -> */, OP_LARROW/* <- */, LPAREN/* ( */, RPAREN/* ) */, 
		LSQUARE/* [ */, RSQUARE/* ] */, SEMI/* ; */, COMMA/* , */, EOF;
	}

	/** Class to represent Tokens. 
	 * 
	 * This is defined as a (non-static) inner class
	 * which means that each Token instance is associated with a specific 
	 * Scanner instance.  We use this when some token methods access the
	 * chars array in the associated Scanner.
	 * 
	 * 
	 * @author Beverly Sanders
	 *
	 */
	public class Token {
		public final Kind kind;
		public final int pos;
		public final int length;
		public final int line;
		public final int pos_in_line;
		public State state;

		public Token(Kind kind, int pos, int length, int line, int pos_in_line) {
			super();
			this.kind = kind;
			this.pos = pos;
			this.length = length;
			this.line = line;
			this.pos_in_line = pos_in_line;
		}

		public String getText() {
			if (kind == Kind.STRING_LITERAL) {
				return chars2String(chars, pos, length);
			}
			else return String.copyValueOf(chars, pos, length);
		}

		/**
		 * To get the text of a StringLiteral, we need to remove the
		 * enclosing " characters and convert escaped characters to
		 * the represented character.  For example the two characters \ t
		 * in the char array should be converted to a single tab character in
		 * the returned String
		 * 
		 * @param chars
		 * @param pos
		 * @param length
		 * @return
		 */
		private String chars2String(char[] chars, int pos, int length) {
			StringBuilder sb = new StringBuilder();
			for (int i = pos + 1; i < pos + length - 1; ++i) {// omit initial and final "
				char ch = chars[i];
				if (ch == '\\') { // handle escape
					i++;
					ch = chars[i];
					switch (ch) {
					case 'b':
						sb.append('\b');
						break;
					case 't':
						sb.append('\t');
						break;
					case 'f':
						sb.append('\f');
						break;
					case 'r':
						sb.append('\r'); //for completeness, line termination chars not allowed in String literals
						break;
					case 'n':
						sb.append('\n'); //for completeness, line termination chars not allowed in String literals
						break;
					case '\"':
						sb.append('\"');
						break;
					case '\'':
						sb.append('\'');
						break;
					case '\\':
						sb.append('\\');
						break;
					default:
						assert false;
						break;
					}
				} else {
					sb.append(ch);
				}
			}
			return sb.toString();
		}

		/**
		 * precondition:  This Token is an INTEGER_LITERAL
		 * 
		 * @returns the integer value represented by the token
		 */
		public int intVal() {
			assert kind == Kind.INTEGER_LITERAL;
			return Integer.valueOf(String.copyValueOf(chars, pos, length));
		}

		public String toString() {
			return "[" + kind + "," + String.copyValueOf(chars, pos, length)  + "," + pos + "," + length + "," + line + ","
					+ pos_in_line + "]";
		}

		/** 
		 * Since we overrode equals, we need to override hashCode.
		 * https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#equals-java.lang.Object-
		 * 
		 * Both the equals and hashCode method were generated by eclipse
		 * 
		 */
		@Override
		public int hashCode() {
			final int prime = 31;
			int result = 1;
			result = prime * result + getOuterType().hashCode();
			result = prime * result + ((kind == null) ? 0 : kind.hashCode());
			result = prime * result + length;
			result = prime * result + line;
			result = prime * result + pos;
			result = prime * result + pos_in_line;
			return result;
		}

		/**
		 * Override equals method to return true if other object
		 * is the same class and all fields are equal.
		 * 
		 * Overriding this creates an obligation to override hashCode.
		 * 
		 * Both hashCode and equals were generated by eclipse.
		 * 
		 */
		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			Token other = (Token) obj;
			if (!getOuterType().equals(other.getOuterType()))
				return false;
			if (kind != other.kind)
				return false;
			if (length != other.length)
				return false;
			if (line != other.line)
				return false;
			if (pos != other.pos)
				return false;
			if (pos_in_line != other.pos_in_line)
				return false;
			return true;
		}

		/**
		 * used in equals to get the Scanner object this Token is 
		 * associated with.
		 * @return
		 */
		private Scanner getOuterType() {
			return Scanner.this;
		}

	}

	/** 
	 * Extra character added to the end of the input characters to simplify the
	 * Scanner.  
	 */
	static final char EOFchar = 0;
	
	/**
	 * The list of tokens created by the scan method.
	 */
	final ArrayList<Token> tokens;
	
	/**
	 * An array of characters representing the input.  These are the characters
	 * from the input string plus and additional EOFchar at the end.
	 */
	final char[] chars;  



	
	/**
	 * position of the next token to be returned by a call to nextToken
	 */
	private int nextTokenPos = 0;

	Scanner(String inputString) {
		int numChars = inputString.length();
		this.chars = Arrays.copyOf(inputString.toCharArray(), numChars + 1); // input string terminated with null char
		chars[numChars] = EOFchar;
		tokens = new ArrayList<Token>();
	}


	/**
	 * Method to scan the input and create a list of Tokens.
	 * 
	 * If an error is encountered during scanning, throw a LexicalException.
	 * 
	 * @return
	 * @throws LexicalException
	 */
	public Scanner scan() throws LexicalException {
		int count = 0;
		String name = "";
		String number = "";
		HashMap<String, Kind> values = new HashMap<>();
		values.put("x", Kind.KW_x);
		values.put("y", Kind.KW_y);
		values.put("X", Kind.KW_X);
		values.put("Y", Kind.KW_Y);
		values.put("r", Kind.KW_r);
		values.put("R", Kind.KW_R);
		values.put("a", Kind.KW_a);
		values.put("A", Kind.KW_A);
		values.put("Z", Kind.KW_Z);
		values.put("DEF_X", Kind.KW_DEF_X);
		values.put("DEF_Y", Kind.KW_DEF_Y);
		values.put("SCREEN", Kind.KW_SCREEN);
		values.put("cart_x", Kind.KW_cart_x);
		values.put("cart_y", Kind.KW_cart_y);
		values.put("polar_a", Kind.KW_polar_a);
		values.put("polar_r", Kind.KW_polar_r);
		values.put("abs", Kind.KW_abs);
		values.put("sin", Kind.KW_sin);
		values.put("cos", Kind.KW_cos);
		values.put("atan", Kind.KW_atan);
		values.put("log", Kind.KW_log);
		values.put("image", Kind.KW_image);
		values.put("int", Kind.KW_int);
		values.put("boolean", Kind.KW_boolean);
		values.put("url", Kind.KW_url);
		values.put("file", Kind.KW_file);
		values.put("true", Kind.BOOLEAN_LITERAL);
		values.put("false", Kind.BOOLEAN_LITERAL);
		
		/* TODO  Replace this with a correct and complete implementation!!! */
		int pos = 0;
		int startPos = pos;
		int line = 1;
		int posInLine = 1;
		State state = State.START;
		while(pos<chars.length){
			char ch = chars[pos];
			switch(state){
			case START:
				switch(ch){
				
				case '\n':
				{
					pos++;
					posInLine = 1;
					startPos = pos;
					line++;
					break;
				}
				
				case '\r':
				{
					state = State.AFTER_RETURN;
					pos++;
					break;
				}
				
				case '>':
		 		{
					//tokens.add(new Token(Kind.OP_GT, startPos, 1, line, posInLine));
					pos++;
					//posInLine++;
					state = State.AFTER_GREATER;
					break;
				}
				
				case '<':
				{
					//tokens.add(new Token(Kind.OP_GT, startPos, 1, line, posInLine));
					pos++;
					//posInLine++;
					state = State.AFTER_LESS;
					break;
				}
				
				case '-':
				{
					//tokens.add(new Token(Kind.OP_MINUS, startPos, 1, line, posInLine));
					pos++;
					//startPos = pos;
					//posInLine++;
					state = State.AFTER_MINUS;
					break;
				}
				
				case '*':
				{
					pos++;
					state = State.AFTER_MULTIPLY;
					break;		
				}
				
				case '"':
				{
					pos++;
					state = State.IN_STRING;
					break;
				}
				
				case '!':
				{
					pos++;
					state = State.AFTER_EXCL;
					break;
				}
				
				case '/':
				{
					//tokens.add(new Token(Kind.OP_DIV, startPos, 1, line, posInLine));
					pos++;
					//startPos = pos;
					//posInLine++;
					state = State.AFTER_DIV;
					break;
				}
				
				case '+':
				{
					tokens.add(new Token(Kind.OP_PLUS, startPos, 1, line, posInLine));
					pos++;
					startPos = pos;
					posInLine++;
					break;
				}
				
				case '%':
				{
					tokens.add(new Token(Kind.OP_MOD, startPos, 1, line, posInLine));
					pos++;
					startPos = pos;
					posInLine++;
					break;
				}
				
				case '|':
				{
					tokens.add(new Token(Kind.OP_OR, startPos, 1, line, posInLine));
					pos++;
					startPos = pos;
					posInLine++;
					break;
				}
				
				case '?':
				{
					tokens.add(new Token(Kind.OP_Q, startPos, 1, line, posInLine));
					pos++;
					startPos = pos;
					posInLine++;
					break;
				}
				
				case ':':
				{
					tokens.add(new Token(Kind.OP_COLON, startPos, 1, line, posInLine));
					pos++;
					startPos = pos;
					posInLine++;
					break;
				}
				
				case '&':
				{
					tokens.add(new Token(Kind.OP_AND, startPos, 1, line, posInLine));
					pos++;
					startPos = pos;
					posInLine++;
					break;
				}
				
				case '@':
				{
					tokens.add(new Token(Kind.OP_AT, startPos, 1, line, posInLine));
					pos++;
					startPos = pos;
					posInLine++;
					break;
				}
				
				case '(':
				{
					tokens.add(new Token(Kind.LPAREN, startPos, 1, line, posInLine));
					pos++;
					startPos = pos;
					posInLine++;
					break;
				}
				
				case ')':
				{
					tokens.add(new Token(Kind.RPAREN, startPos, 1, line, posInLine));
					pos++;
					startPos = pos;
					posInLine++;
					break;
				}
				
				case '[':
				{
					tokens.add(new Token(Kind.LSQUARE, startPos, 1, line, posInLine));
					pos++;
					startPos = pos;
					posInLine++;
					break;
				}
				
				case ']':
				{
					tokens.add(new Token(Kind.RSQUARE, startPos, 1, line, posInLine));
					pos++;
					startPos = pos;
					posInLine++;
					break;
				}
				
				case ';':
				{
					tokens.add(new Token(Kind.SEMI, startPos, 1, line, posInLine));
					pos++;
					startPos = pos;
					posInLine++;
					break;
				}
				
				case ',':
				{
					tokens.add(new Token(Kind.COMMA, startPos, 1, line, posInLine));
					pos++;
					startPos = pos;
					posInLine++;
					break;
				}
				
				case '0':
				{
					tokens.add(new Token(Kind.INTEGER_LITERAL, pos, 1, line, posInLine));
					pos++;
					startPos = pos;
					posInLine++;
					break;
				}
				
				case '=':
				{
					//tokens.add(new Token(Kind.OP_ASSIGN, pos, 1, line, posInLine));
					pos++;
					//posInLine++;
					state = State.AFTER_EQ;
					break;
				}
					
				case EOFchar:
				{
					//pos++;
					//posInLine++;
					tokens.add(new Token(Kind.EOF, pos, 0, line, posInLine));
					return this;
				}
				
				default:
				{
					if(Character.isDigit(ch)){
						state = State.IN_DIGIT;
						//tokens.add(new Token(Kind.INTEGER_LITERAL, startPos, 1, line, posInLine));
						pos++;
						//posInLine++;
					}
					
					else if(Character.isJavaIdentifierStart(ch)){
						state = State.IN_IDENT;
						//tokens.add(new Token(Kind.IDENTIFIER, pos, 1, line, posInLine));
						pos++;
						//posInLine++;
					}
					
					else if(Character.isWhitespace(ch)){
						pos++;
						posInLine++;
						startPos = pos;
						state = State.START;
					}
					else{
						throw new LexicalException("Invalid Input character", pos);
					}
				}
				}
				break;
				
			case IN_IDENT:				
				//String name = "";
				name = name + chars[pos-1];
				//sb.append(chars[pos-1]);
				
				if(Character.isLetterOrDigit(ch) || ch == '_' || ch == '$'){
					//tokens.add(new Token(Kind.IDENTIFIER, pos, 1, line, posInLine));
					pos++;
					//posInLine++;
				}
				else{
					//System.out.println(name);
					if(values.containsKey(name)){
						tokens.add(new Token(values.get(name), startPos, pos-startPos, line, posInLine));
						posInLine = posInLine + pos - startPos;
						startPos = pos;
						state = State.START;
						name = "";
					}
					else{
						tokens.add(new Token(Kind.IDENTIFIER, startPos, pos-startPos, line, posInLine));
						posInLine = posInLine + pos - startPos;
						startPos = pos;
						state = State.START;
						name = "";
					}
				}
				break;
				
			case IN_DIGIT:
				number = number + chars[pos-1];
				
				if(Character.isDigit(ch)){
					//tokens.add(new Token(Kind.INTEGER_LITERAL, pos, 1, line, posInLine));
					pos++;
					//posInLine++;
				}
				else{
					try{
						int input = Integer.parseInt(number);
						tokens.add(new Token(Kind.INTEGER_LITERAL, startPos, pos-startPos, line, posInLine));
						posInLine = posInLine + pos - startPos;
						startPos = pos;
						state = State.START;
						number = "";
					}
					catch(NumberFormatException e){
						throw new LexicalException("Invalid Integer", startPos);
					}
				}
				break;
				
			case AFTER_EQ:
				if(ch == '='){
					pos++;
					tokens.add(new Token(Kind.OP_EQ, startPos, pos-startPos, line, posInLine));
					posInLine = posInLine + pos - startPos;
					startPos = pos;
					state = State.START;
				}
				else{
					tokens.add(new Token(Kind.OP_ASSIGN, startPos, pos-startPos, line, posInLine));
					posInLine = posInLine + pos - startPos;
					startPos = pos;
					state = State.START;
				}
				break;
				
			case AFTER_GREATER:
				if(ch == '='){
					pos++;
					tokens.add(new Token(Kind.OP_GE, startPos, pos-startPos, line, posInLine));
					posInLine = posInLine + pos - startPos;
					startPos = pos;
					state = State.START;
				}
				else{
					//pos++;
					tokens.add(new Token(Kind.OP_GT, startPos, pos-startPos, line, posInLine));
					posInLine = posInLine + pos - startPos;
					startPos = pos;
					state = State.START;
				}
				break;
				
			case AFTER_LESS:
				if(ch == '-'){
					pos++;
					tokens.add(new Token(Kind.OP_LARROW, startPos, pos-startPos, line, posInLine));
					posInLine = posInLine + pos - startPos;
					startPos = pos;
					state = State.START;
				}
				
				else if(ch == '='){
					pos++;
					tokens.add(new Token(Kind.OP_LE, startPos, pos-startPos, line, posInLine));
					posInLine = posInLine + pos - startPos;
					startPos = pos;
					state = State.START;
				}
				
				else{
					tokens.add(new Token(Kind.OP_LT, startPos, pos-startPos, line, posInLine));
					posInLine = posInLine + pos - startPos;
					startPos = pos;
					state = State.START;
				}
				break;
				
			case AFTER_MINUS:
				if(ch == '>'){
					pos++;
					tokens.add(new Token(Kind.OP_RARROW, startPos, pos-startPos, line, posInLine));
					posInLine = posInLine + pos - startPos;
					startPos = pos;
					state = State.START;
					
				}
				
				else{
					tokens.add(new Token(Kind.OP_MINUS, startPos, pos-startPos, line, posInLine));
					posInLine = posInLine + pos - startPos;
					startPos = pos;
					state = State.START;
				}
				break;
				
			case AFTER_MULTIPLY:
				if(ch == '*'){
					pos++;
					tokens.add(new Token(Kind.OP_POWER, startPos, pos-startPos, line, posInLine));
					posInLine = posInLine + pos - startPos;
					startPos = pos;
					state = State.START;
				}
				
				else{
					tokens.add(new Token(Kind.OP_TIMES, startPos, pos-startPos, line, posInLine));
					posInLine = posInLine + pos - startPos;
					startPos = pos;
					state = State.START;
				}
				break;
				
			case AFTER_EXCL:
				if(ch == '='){
					pos++;
					tokens.add(new Token(Kind.OP_NEQ, startPos, pos-startPos, line, posInLine));
					posInLine = posInLine + pos - startPos;
					startPos = pos;
					state = State.START;
				}
				
				else{
					tokens.add(new Token(Kind.OP_EXCL, startPos, pos-startPos, line, posInLine));
					posInLine = posInLine + pos - startPos;
					startPos = pos;
					state = State.START;
				}
				break;
				
			case AFTER_RETURN:
				if(ch == '\n'){
					startPos = startPos + 2;
					pos++;
					posInLine = 1;
					line++;
					state = State.START;
				}
				
				else{
					startPos++;
					posInLine = 1;
					line++;
					state = State.START;
				}
				break;
				
			case AFTER_DIV:
				if(ch == '/'){
					pos++;
					state = State.AFTER_COMMENT;
				}
				
				else{
					tokens.add(new Token(Kind.OP_DIV, startPos, pos-startPos, line, posInLine));
					posInLine = posInLine + pos - startPos;
					startPos = pos;
					state = State.START;
				}
				break;
				
			case AFTER_COMMENT:
				char a;
				a = chars[pos];
				count = 0;
				//pos++;
				while(a != '\n' && a != '\r' && a != EOFchar){
					pos++;
					a = chars[pos];
					count++;
				}
				if(a == EOFchar){
					state = State.START;
					break;
				}
				if(a == '\r'){
					startPos = startPos + 2 + count;
					pos++;
					state = State.AFTER_RETURN;
					break;
				}
				//line++;
				startPos = pos;
				state = State.START;
				break;
				
			case IN_STRING:
			{
				char b = chars[pos];
				while(b != '\n' && b != '\r' && b != '"' && b != EOFchar){
					/*pos++;
					b = chars[pos];*/
					if(b == '\\'){
						pos++;
						if(chars[pos] == '\"' || chars[pos] == '\'' || chars[pos] == '\\' || chars[pos] =='b' || chars[pos] =='t' || chars[pos] =='n' || chars[pos] =='f' || chars[pos] =='r'){
							pos++;
							b = chars[pos];
						}
						else{
							throw new LexicalException("Single slash is not allowed in the string", pos);
						}
					}
					else{
						pos++;
						b = chars[pos];
					}
				}
				if(b == EOFchar){
					throw new LexicalException("Unclosed String", pos);
				}
				else if(b == '"'){
					pos++;
					tokens.add(new Token(Kind.STRING_LITERAL, startPos, pos-startPos, line, posInLine));
					posInLine = posInLine + pos - startPos;
					startPos = pos;
					state = State.START;
				}
				else if(b == '\n' || b == '\r'){
					throw new LexicalException("CR and LF line terminators are not allowed in the string", pos);
				}
			}	
		}
		}
		//tokens.add(new Token(Kind.EOF, pos, 0, line, posInLine));
		return this;

	}


	/**
	 * Returns true if the internal interator has more Tokens
	 * 
	 * @return
	 */
	public boolean hasTokens() {
		return nextTokenPos < tokens.size();
	}

	/**
	 * Returns the next Token and updates the internal iterator so that
	 * the next call to nextToken will return the next token in the list.
	 * 
	 * It is the callers responsibility to ensure that there is another Token.
	 * 
	 * Precondition:  hasTokens()
	 * @return
	 */
	public Token nextToken() {
		return tokens.get(nextTokenPos++);
	}
	
	/**
	 * Returns the next Token, but does not update the internal iterator.
	 * This means that the next call to nextToken or peek will return the
	 * same Token as returned by this methods.
	 * 
	 * It is the callers responsibility to ensure that there is another Token.
	 * 
	 * Precondition:  hasTokens()
	 * 
	 * @return next Token.
	 */
	public Token peek() {
		return tokens.get(nextTokenPos);
	}
	
	
	/**
	 * Resets the internal iterator so that the next call to peek or nextToken
	 * will return the first Token.
	 */
	public void reset() {
		nextTokenPos = 0;
	}

	/**
	 * Returns a String representation of the list of Tokens 
	 */
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("Tokens:\n");
		for (int i = 0; i < tokens.size(); i++) {
			sb.append(tokens.get(i)).append('\n');
		}
		return sb.toString();
	}

}
